

CREATE TABLE BRAND (ID BIGINT, NAME varchar(20) );
CREATE TABLE TOOL_TYPE (ID BIGINT, NAME varchar(20), DAILY_CHARGE int, WEEKDAY_CHARGE int, WEEKEND_CHARGE int, HOLIDAY_CHARGE int);
CREATE TABLE TOOLS (ID BIGINT, CODE varchar(4), TOOL_TYPE_ID int, BRAND_ID int);