CREATE TABLE BRAND
(
    ID   BIGINT      NOT NULL,
    NAME varchar(20) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TOOL_TYPE
(
    ID             BIGINT      NOT NULL,
    NAME           varchar(20) NOT NULL,
    DAILY_CHARGE   float       NOT NULL,
    WEEKDAY_CHARGE int         NOT NULL,
    WEEKEND_CHARGE int         NOT NULL,
    HOLIDAY_CHARGE int         NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TOOLS
(
    ID           BIGINT     NOT NULL,
    CODE         varchar(4) NOT NULL UNIQUE,
    TOOL_TYPE_ID int        NOT NULL,
    BRAND_ID     int        NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_tool_type FOREIGN KEY (TOOL_TYPE_ID) REFERENCES TOOL_TYPE (ID),
    CONSTRAINT fk_brand FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID)
);